---
# tasks file for repos

- name: copy over template for yum repo file
  template:
    src: /path/to/file/repos.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
  notify: clean yum repos cache
